### ISSUE TITLE
What do you think of my new site, Hurl?

### ISSUE THREAD

**Issue by geoffw8** [aeden/ama#5]
Its part social network, part bookmarking site. Sign up @ http://www.hurl.io/users/sign_up and follow me http://www.hurl.io/geoff - I think you'll like it. You'll be the first person I don't know who joins and I'd love some feedback.

I use it myself, I think its pretty cool. Hope you don't think this is too spammy. Value your opinion :) Posted it up to betali.st last night and going to start the push, when I saw your offer I thought I'd take the opportunity.

Cheers
Geoff

**Comment by aeden** [comment]
I'll answer your question with my own questions:
- Are you building this for fun and as a learning experience, or are you expecting to build a business out of it?
- Why is hurl better than everything else before it?
- Why should I spend my time and energy on your service versus the other social bookmarking services that are already out there?

My gut reaction is: "A social bookmarking site, moving on then" so you'll need to really blow my mind to convince me to sign up, and I think I'm won't be alone in thinking this.

**Comment by geoffw8** [comment]
Thanks for getting back to me.

All of the above, really. For fun, if it starts to gain traction and people feel it adds value I'll see how I can monetize it.

I'm not sure "Bookmarking" site is really the best way to describe the site in all honesty, its something I thought about quite a lot and I wonder if I've landed on the wrong answer.

Really what sits at the heart of Hurl is your feed, the incoming stream of posts (links/content) from users you follow. For example if you take a look at my profile (http://www.hurl.io/geoff) you will see I tend to share blogs, videos, tweets, slideshare decks related to startups, development, growth, business and other misc items. What I'm saying first when I post these things to Hurl is not "I want this for my own future reference", but "I think you should see this", I think thats the break from really a bookmarking site, to I guess what Hurl is, a site for sharing. In fact, I still use my browser bookmarks - not everything is for Hurl. 

What this means is Hurl becomes a platform for discovering and sharing things you find interesting across any number of topics, be it health, business, sports or agriculture. In return for spending your time and energy on it you get the benefit of the network, the army of similar minded individuals who are happy to share stuff that you would be happy to see into the network in return for you doing the same. Every item inside of Hurl has been added because someone, someone you follow has endorsed it for _some_ reason.

The way I see it is, when you find something what do you do? Bookmark it? Maybe post it to a friends Facebook timeline/inbox/a group? Tweet it? Email it to a few people? What do you do then if you want to find it later? Trawl through their timelines? Whatever you do it takes more clicks and more time than it would if you were using Hurl. If instead you use Hurl's bookmarklet to post it to Hurl, give it a few tags and click save - you can use 'The Launchpad' to get it out to your social networks in a couple of clicks, whilst retaining a reference to it in Hurl (just clicked Saved items) and you're adding value to the network.

Another way I've thought of it in the social world is:
Facebook owns your friends.
Instagram owns your photos.
Twitter owns your conversations.
What owns your things? It certainly isn't delicious.

I appreciated your comments, its definitely got me thinking and has been very valuable. Hopefully I've explained clearly how I feel its different because I do believe there isn't anything like it, its a different kind of tool one that I don't think has been tried before in this way.

**Comment by aeden** [comment]
> Really what sits at the heart of Hurl is your feed, the incoming stream of posts (links/content) from users you follow.

Funny enough, this is exactly what we tried to do with chi.mp. It's a huge challenge though because people don't want a new social network, they want to aggregate (or so they think) but then when they aggregate they realize it's just too much data, so they want context sensitive filtering, and _that_ is a much harder problem to deal with.

Best of luck with it. If you ever feel like bouncing ideas off feel free to just contact me directly.
